#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-portray
Version  : 1.7.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/c0/a2/490649f03504ecdfba362cff4f830b08f3687ad1479234a37adcb495789f/portray-1.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c0/a2/490649f03504ecdfba362cff4f830b08f3687ad1479234a37adcb495789f/portray-1.7.0.tar.gz
Summary  : Your Project with Great Documentation
Group    : Development/Tools
License  : MIT
Requires: pypi-portray-bin = %{version}-%{release}
Requires: pypi-portray-python = %{version}-%{release}
Requires: pypi-portray-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry)

%description
[![portray - Your Project with Great Documentation.](https://raw.github.com/timothycrosley/portray/main/art/logo.png)](https://timothycrosley.github.io/portray/)
_________________

%package bin
Summary: bin components for the pypi-portray package.
Group: Binaries

%description bin
bin components for the pypi-portray package.


%package python
Summary: python components for the pypi-portray package.
Group: Default
Requires: pypi-portray-python3 = %{version}-%{release}

%description python
python components for the pypi-portray package.


%package python3
Summary: python3 components for the pypi-portray package.
Group: Default
Requires: python3-core
Provides: pypi(portray)
Requires: pypi(gitpython)
Requires: pypi(hug)
Requires: pypi(livereload)
Requires: pypi(mkdocs)
Requires: pypi(mkdocs_material)
Requires: pypi(pdocs)
Requires: pypi(pymdown_extensions)
Requires: pypi(toml)
Requires: pypi(yaspin)

%description python3
python3 components for the pypi-portray package.


%prep
%setup -q -n portray-1.7.0
cd %{_builddir}/portray-1.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641522475
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/portray

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
